name: Deploy from master branch to server
on:
  push:
    branches:
      - "main"
jobs:
  docker_publish:
    name: Docker Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ github.token }}
    - name: Build and publish a Docker image for ${{ github.repository }}-ui
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}-ui
        github_token: ${{ github.token }}
        dockerfile: ./web-app/Dockerfile
        context: ./web-app
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ github.token }}
        dockerfile: ./Dockerfile
        context: ./
    - name: Pull and Up docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login ghcr.io -u USERNAME -p ${{ secrets.TOKEN }};
          docker-compose pull;
          docker-compose up -d;
          docker system prune -f
        name: ci  